/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppResearchRouteImport } from './routes/_app/research'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppDocumentationRouteImport } from './routes/_app/documentation'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppPracticeIndexRouteImport } from './routes/_app/practice/index'
import { Route as AppLearnIndexRouteImport } from './routes/_app/learn/index'
import { Route as AppInterviewQaIndexRouteImport } from './routes/_app/interview-qa/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppDsaIndexRouteImport } from './routes/_app/dsa/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as AppCaseStudiesIndexRouteImport } from './routes/_app/case-studies/index'
import { Route as AppAssessmentsIndexRouteImport } from './routes/_app/assessments/index'
import { Route as AppProfileCertificatesRouteImport } from './routes/_app/profile/certificates'
import { Route as AppProfileAchievementsRouteImport } from './routes/_app/profile/achievements'
import { Route as AppLearnRoadmapsRouteImport } from './routes/_app/learn/roadmaps'
import { Route as AppLearnNotesRouteImport } from './routes/_app/learn/notes'
import { Route as AppInterviewQaTypeRouteImport } from './routes/_app/interview-qa/$type'
import { Route as AppEventsTypeRouteImport } from './routes/_app/events/$type'
import { Route as AppDsaTopicIdRouteImport } from './routes/_app/dsa/$topicId'
import { Route as AppDashboardAiDashboardRouteImport } from './routes/_app/dashboard/ai-dashboard'
import { Route as AppCoursesBookmarksRouteImport } from './routes/_app/courses/bookmarks'
import { Route as AppCaseStudiesTypeRouteImport } from './routes/_app/case-studies/$type'
import { Route as AppAssessmentsTypeRouteImport } from './routes/_app/assessments/$type'
import { Route as AppAiResearchRouteImport } from './routes/_app/ai/research'
import { Route as AppAiChatRouteImport } from './routes/_app/ai/chat'
import { Route as AppCoursesCourseIdIndexRouteImport } from './routes/_app/courses/$courseId/index'
import { Route as AppCoursesCourseIdArticlesRouteImport } from './routes/_app/courses/$courseId/articles'
import { Route as AppCoursesCourseIdModulesModuleIdIndexRouteImport } from './routes/_app/courses/$courseId/modules/$moduleId/index'
import { Route as AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRouteImport } from './routes/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentationRoute = AppDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeIndexRoute = AppPracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnIndexRoute = AppLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewQaIndexRoute = AppInterviewQaIndexRouteImport.update({
  id: '/interview-qa/',
  path: '/interview-qa/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppDsaIndexRoute = AppDsaIndexRouteImport.update({
  id: '/dsa/',
  path: '/dsa/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseStudiesIndexRoute = AppCaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsIndexRoute = AppAssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileCertificatesRoute = AppProfileCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileAchievementsRoute = AppProfileAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppLearnRoadmapsRoute = AppLearnRoadmapsRouteImport.update({
  id: '/learn/roadmaps',
  path: '/learn/roadmaps',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnNotesRoute = AppLearnNotesRouteImport.update({
  id: '/learn/notes',
  path: '/learn/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewQaTypeRoute = AppInterviewQaTypeRouteImport.update({
  id: '/interview-qa/$type',
  path: '/interview-qa/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsTypeRoute = AppEventsTypeRouteImport.update({
  id: '/events/$type',
  path: '/events/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppDsaTopicIdRoute = AppDsaTopicIdRouteImport.update({
  id: '/dsa/$topicId',
  path: '/dsa/$topicId',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardAiDashboardRoute = AppDashboardAiDashboardRouteImport.update({
  id: '/dashboard/ai-dashboard',
  path: '/dashboard/ai-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesBookmarksRoute = AppCoursesBookmarksRouteImport.update({
  id: '/courses/bookmarks',
  path: '/courses/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseStudiesTypeRoute = AppCaseStudiesTypeRouteImport.update({
  id: '/case-studies/$type',
  path: '/case-studies/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsTypeRoute = AppAssessmentsTypeRouteImport.update({
  id: '/assessments/$type',
  path: '/assessments/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppAiResearchRoute = AppAiResearchRouteImport.update({
  id: '/ai/research',
  path: '/ai/research',
  getParentRoute: () => AppRoute,
} as any)
const AppAiChatRoute = AppAiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCourseIdIndexRoute = AppCoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCourseIdArticlesRoute =
  AppCoursesCourseIdArticlesRouteImport.update({
    id: '/courses/$courseId/articles',
    path: '/courses/$courseId/articles',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseIdModulesModuleIdIndexRoute =
  AppCoursesCourseIdModulesModuleIdIndexRouteImport.update({
    id: '/courses/$courseId/modules/$moduleId/',
    path: '/courses/$courseId/modules/$moduleId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute =
  AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRouteImport.update({
    id: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/',
    path: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof AppCommunityRoute
  '/documentation': typeof AppDocumentationRoute
  '/help': typeof AppHelpRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/research': typeof AppResearchRoute
  '/ai/chat': typeof AppAiChatRoute
  '/ai/research': typeof AppAiResearchRoute
  '/assessments/$type': typeof AppAssessmentsTypeRoute
  '/case-studies/$type': typeof AppCaseStudiesTypeRoute
  '/courses/bookmarks': typeof AppCoursesBookmarksRoute
  '/dashboard/ai-dashboard': typeof AppDashboardAiDashboardRoute
  '/dsa/$topicId': typeof AppDsaTopicIdRoute
  '/events/$type': typeof AppEventsTypeRoute
  '/interview-qa/$type': typeof AppInterviewQaTypeRoute
  '/learn/notes': typeof AppLearnNotesRoute
  '/learn/roadmaps': typeof AppLearnRoadmapsRoute
  '/profile/achievements': typeof AppProfileAchievementsRoute
  '/profile/certificates': typeof AppProfileCertificatesRoute
  '/assessments/': typeof AppAssessmentsIndexRoute
  '/case-studies/': typeof AppCaseStudiesIndexRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dsa/': typeof AppDsaIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/interview-qa/': typeof AppInterviewQaIndexRoute
  '/learn/': typeof AppLearnIndexRoute
  '/practice/': typeof AppPracticeIndexRoute
  '/courses/$courseId/articles': typeof AppCoursesCourseIdArticlesRoute
  '/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/courses/$courseId/modules/$moduleId/': typeof AppCoursesCourseIdModulesModuleIdIndexRoute
  '/courses/$courseId/modules/$moduleId/lessons/$lessonId/': typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof AppCommunityRoute
  '/documentation': typeof AppDocumentationRoute
  '/help': typeof AppHelpRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/research': typeof AppResearchRoute
  '/ai/chat': typeof AppAiChatRoute
  '/ai/research': typeof AppAiResearchRoute
  '/assessments/$type': typeof AppAssessmentsTypeRoute
  '/case-studies/$type': typeof AppCaseStudiesTypeRoute
  '/courses/bookmarks': typeof AppCoursesBookmarksRoute
  '/dashboard/ai-dashboard': typeof AppDashboardAiDashboardRoute
  '/dsa/$topicId': typeof AppDsaTopicIdRoute
  '/events/$type': typeof AppEventsTypeRoute
  '/interview-qa/$type': typeof AppInterviewQaTypeRoute
  '/learn/notes': typeof AppLearnNotesRoute
  '/learn/roadmaps': typeof AppLearnRoadmapsRoute
  '/profile/achievements': typeof AppProfileAchievementsRoute
  '/profile/certificates': typeof AppProfileCertificatesRoute
  '/assessments': typeof AppAssessmentsIndexRoute
  '/case-studies': typeof AppCaseStudiesIndexRoute
  '/courses': typeof AppCoursesIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dsa': typeof AppDsaIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/interview-qa': typeof AppInterviewQaIndexRoute
  '/learn': typeof AppLearnIndexRoute
  '/practice': typeof AppPracticeIndexRoute
  '/courses/$courseId/articles': typeof AppCoursesCourseIdArticlesRoute
  '/courses/$courseId': typeof AppCoursesCourseIdIndexRoute
  '/courses/$courseId/modules/$moduleId': typeof AppCoursesCourseIdModulesModuleIdIndexRoute
  '/courses/$courseId/modules/$moduleId/lessons/$lessonId': typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/community': typeof AppCommunityRoute
  '/_app/documentation': typeof AppDocumentationRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/research': typeof AppResearchRoute
  '/_app/ai/chat': typeof AppAiChatRoute
  '/_app/ai/research': typeof AppAiResearchRoute
  '/_app/assessments/$type': typeof AppAssessmentsTypeRoute
  '/_app/case-studies/$type': typeof AppCaseStudiesTypeRoute
  '/_app/courses/bookmarks': typeof AppCoursesBookmarksRoute
  '/_app/dashboard/ai-dashboard': typeof AppDashboardAiDashboardRoute
  '/_app/dsa/$topicId': typeof AppDsaTopicIdRoute
  '/_app/events/$type': typeof AppEventsTypeRoute
  '/_app/interview-qa/$type': typeof AppInterviewQaTypeRoute
  '/_app/learn/notes': typeof AppLearnNotesRoute
  '/_app/learn/roadmaps': typeof AppLearnRoadmapsRoute
  '/_app/profile/achievements': typeof AppProfileAchievementsRoute
  '/_app/profile/certificates': typeof AppProfileCertificatesRoute
  '/_app/assessments/': typeof AppAssessmentsIndexRoute
  '/_app/case-studies/': typeof AppCaseStudiesIndexRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dsa/': typeof AppDsaIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/interview-qa/': typeof AppInterviewQaIndexRoute
  '/_app/learn/': typeof AppLearnIndexRoute
  '/_app/practice/': typeof AppPracticeIndexRoute
  '/_app/courses/$courseId/articles': typeof AppCoursesCourseIdArticlesRoute
  '/_app/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/_app/courses/$courseId/modules/$moduleId/': typeof AppCoursesCourseIdModulesModuleIdIndexRoute
  '/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/': typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/documentation'
    | '/help'
    | '/profile'
    | '/research'
    | '/ai/chat'
    | '/ai/research'
    | '/assessments/$type'
    | '/case-studies/$type'
    | '/courses/bookmarks'
    | '/dashboard/ai-dashboard'
    | '/dsa/$topicId'
    | '/events/$type'
    | '/interview-qa/$type'
    | '/learn/notes'
    | '/learn/roadmaps'
    | '/profile/achievements'
    | '/profile/certificates'
    | '/assessments/'
    | '/case-studies/'
    | '/courses/'
    | '/dashboard/'
    | '/dsa/'
    | '/events/'
    | '/interview-qa/'
    | '/learn/'
    | '/practice/'
    | '/courses/$courseId/articles'
    | '/courses/$courseId/'
    | '/courses/$courseId/modules/$moduleId/'
    | '/courses/$courseId/modules/$moduleId/lessons/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/documentation'
    | '/help'
    | '/profile'
    | '/research'
    | '/ai/chat'
    | '/ai/research'
    | '/assessments/$type'
    | '/case-studies/$type'
    | '/courses/bookmarks'
    | '/dashboard/ai-dashboard'
    | '/dsa/$topicId'
    | '/events/$type'
    | '/interview-qa/$type'
    | '/learn/notes'
    | '/learn/roadmaps'
    | '/profile/achievements'
    | '/profile/certificates'
    | '/assessments'
    | '/case-studies'
    | '/courses'
    | '/dashboard'
    | '/dsa'
    | '/events'
    | '/interview-qa'
    | '/learn'
    | '/practice'
    | '/courses/$courseId/articles'
    | '/courses/$courseId'
    | '/courses/$courseId/modules/$moduleId'
    | '/courses/$courseId/modules/$moduleId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/community'
    | '/_app/documentation'
    | '/_app/help'
    | '/_app/profile'
    | '/_app/research'
    | '/_app/ai/chat'
    | '/_app/ai/research'
    | '/_app/assessments/$type'
    | '/_app/case-studies/$type'
    | '/_app/courses/bookmarks'
    | '/_app/dashboard/ai-dashboard'
    | '/_app/dsa/$topicId'
    | '/_app/events/$type'
    | '/_app/interview-qa/$type'
    | '/_app/learn/notes'
    | '/_app/learn/roadmaps'
    | '/_app/profile/achievements'
    | '/_app/profile/certificates'
    | '/_app/assessments/'
    | '/_app/case-studies/'
    | '/_app/courses/'
    | '/_app/dashboard/'
    | '/_app/dsa/'
    | '/_app/events/'
    | '/_app/interview-qa/'
    | '/_app/learn/'
    | '/_app/practice/'
    | '/_app/courses/$courseId/articles'
    | '/_app/courses/$courseId/'
    | '/_app/courses/$courseId/modules/$moduleId/'
    | '/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/research': {
      id: '/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentation': {
      id: '/_app/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AppDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/': {
      id: '/_app/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AppPracticeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/': {
      id: '/_app/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AppLearnIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview-qa/': {
      id: '/_app/interview-qa/'
      path: '/interview-qa'
      fullPath: '/interview-qa/'
      preLoaderRoute: typeof AppInterviewQaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dsa/': {
      id: '/_app/dsa/'
      path: '/dsa'
      fullPath: '/dsa/'
      preLoaderRoute: typeof AppDsaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-studies/': {
      id: '/_app/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof AppCaseStudiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessments/': {
      id: '/_app/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AppAssessmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/certificates': {
      id: '/_app/profile/certificates'
      path: '/certificates'
      fullPath: '/profile/certificates'
      preLoaderRoute: typeof AppProfileCertificatesRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/achievements': {
      id: '/_app/profile/achievements'
      path: '/achievements'
      fullPath: '/profile/achievements'
      preLoaderRoute: typeof AppProfileAchievementsRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/learn/roadmaps': {
      id: '/_app/learn/roadmaps'
      path: '/learn/roadmaps'
      fullPath: '/learn/roadmaps'
      preLoaderRoute: typeof AppLearnRoadmapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/notes': {
      id: '/_app/learn/notes'
      path: '/learn/notes'
      fullPath: '/learn/notes'
      preLoaderRoute: typeof AppLearnNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview-qa/$type': {
      id: '/_app/interview-qa/$type'
      path: '/interview-qa/$type'
      fullPath: '/interview-qa/$type'
      preLoaderRoute: typeof AppInterviewQaTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$type': {
      id: '/_app/events/$type'
      path: '/events/$type'
      fullPath: '/events/$type'
      preLoaderRoute: typeof AppEventsTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dsa/$topicId': {
      id: '/_app/dsa/$topicId'
      path: '/dsa/$topicId'
      fullPath: '/dsa/$topicId'
      preLoaderRoute: typeof AppDsaTopicIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/ai-dashboard': {
      id: '/_app/dashboard/ai-dashboard'
      path: '/dashboard/ai-dashboard'
      fullPath: '/dashboard/ai-dashboard'
      preLoaderRoute: typeof AppDashboardAiDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/bookmarks': {
      id: '/_app/courses/bookmarks'
      path: '/courses/bookmarks'
      fullPath: '/courses/bookmarks'
      preLoaderRoute: typeof AppCoursesBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-studies/$type': {
      id: '/_app/case-studies/$type'
      path: '/case-studies/$type'
      fullPath: '/case-studies/$type'
      preLoaderRoute: typeof AppCaseStudiesTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessments/$type': {
      id: '/_app/assessments/$type'
      path: '/assessments/$type'
      fullPath: '/assessments/$type'
      preLoaderRoute: typeof AppAssessmentsTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/research': {
      id: '/_app/ai/research'
      path: '/ai/research'
      fullPath: '/ai/research'
      preLoaderRoute: typeof AppAiResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/chat': {
      id: '/_app/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AppAiChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$courseId/': {
      id: '/_app/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof AppCoursesCourseIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$courseId/articles': {
      id: '/_app/courses/$courseId/articles'
      path: '/courses/$courseId/articles'
      fullPath: '/courses/$courseId/articles'
      preLoaderRoute: typeof AppCoursesCourseIdArticlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$courseId/modules/$moduleId/': {
      id: '/_app/courses/$courseId/modules/$moduleId/'
      path: '/courses/$courseId/modules/$moduleId'
      fullPath: '/courses/$courseId/modules/$moduleId/'
      preLoaderRoute: typeof AppCoursesCourseIdModulesModuleIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/': {
      id: '/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/'
      path: '/courses/$courseId/modules/$moduleId/lessons/$lessonId'
      fullPath: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/'
      preLoaderRoute: typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileAchievementsRoute: typeof AppProfileAchievementsRoute
  AppProfileCertificatesRoute: typeof AppProfileCertificatesRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileAchievementsRoute: AppProfileAchievementsRoute,
  AppProfileCertificatesRoute: AppProfileCertificatesRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppCommunityRoute: typeof AppCommunityRoute
  AppDocumentationRoute: typeof AppDocumentationRoute
  AppHelpRoute: typeof AppHelpRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppResearchRoute: typeof AppResearchRoute
  AppAiChatRoute: typeof AppAiChatRoute
  AppAiResearchRoute: typeof AppAiResearchRoute
  AppAssessmentsTypeRoute: typeof AppAssessmentsTypeRoute
  AppCaseStudiesTypeRoute: typeof AppCaseStudiesTypeRoute
  AppCoursesBookmarksRoute: typeof AppCoursesBookmarksRoute
  AppDashboardAiDashboardRoute: typeof AppDashboardAiDashboardRoute
  AppDsaTopicIdRoute: typeof AppDsaTopicIdRoute
  AppEventsTypeRoute: typeof AppEventsTypeRoute
  AppInterviewQaTypeRoute: typeof AppInterviewQaTypeRoute
  AppLearnNotesRoute: typeof AppLearnNotesRoute
  AppLearnRoadmapsRoute: typeof AppLearnRoadmapsRoute
  AppAssessmentsIndexRoute: typeof AppAssessmentsIndexRoute
  AppCaseStudiesIndexRoute: typeof AppCaseStudiesIndexRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDsaIndexRoute: typeof AppDsaIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppInterviewQaIndexRoute: typeof AppInterviewQaIndexRoute
  AppLearnIndexRoute: typeof AppLearnIndexRoute
  AppPracticeIndexRoute: typeof AppPracticeIndexRoute
  AppCoursesCourseIdArticlesRoute: typeof AppCoursesCourseIdArticlesRoute
  AppCoursesCourseIdIndexRoute: typeof AppCoursesCourseIdIndexRoute
  AppCoursesCourseIdModulesModuleIdIndexRoute: typeof AppCoursesCourseIdModulesModuleIdIndexRoute
  AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute: typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityRoute: AppCommunityRoute,
  AppDocumentationRoute: AppDocumentationRoute,
  AppHelpRoute: AppHelpRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppResearchRoute: AppResearchRoute,
  AppAiChatRoute: AppAiChatRoute,
  AppAiResearchRoute: AppAiResearchRoute,
  AppAssessmentsTypeRoute: AppAssessmentsTypeRoute,
  AppCaseStudiesTypeRoute: AppCaseStudiesTypeRoute,
  AppCoursesBookmarksRoute: AppCoursesBookmarksRoute,
  AppDashboardAiDashboardRoute: AppDashboardAiDashboardRoute,
  AppDsaTopicIdRoute: AppDsaTopicIdRoute,
  AppEventsTypeRoute: AppEventsTypeRoute,
  AppInterviewQaTypeRoute: AppInterviewQaTypeRoute,
  AppLearnNotesRoute: AppLearnNotesRoute,
  AppLearnRoadmapsRoute: AppLearnRoadmapsRoute,
  AppAssessmentsIndexRoute: AppAssessmentsIndexRoute,
  AppCaseStudiesIndexRoute: AppCaseStudiesIndexRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDsaIndexRoute: AppDsaIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppInterviewQaIndexRoute: AppInterviewQaIndexRoute,
  AppLearnIndexRoute: AppLearnIndexRoute,
  AppPracticeIndexRoute: AppPracticeIndexRoute,
  AppCoursesCourseIdArticlesRoute: AppCoursesCourseIdArticlesRoute,
  AppCoursesCourseIdIndexRoute: AppCoursesCourseIdIndexRoute,
  AppCoursesCourseIdModulesModuleIdIndexRoute:
    AppCoursesCourseIdModulesModuleIdIndexRoute,
  AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute:
    AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
