/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppResearchRouteImport } from './routes/_app/research'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPracticeRouteImport } from './routes/_app/practice'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppDocumentationRouteImport } from './routes/_app/documentation'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppPracticeIndexRouteImport } from './routes/_app/practice/index'
import { Route as AppLearnIndexRouteImport } from './routes/_app/learn/index'
import { Route as AppInterviewQaIndexRouteImport } from './routes/_app/interview-qa/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppDsaIndexRouteImport } from './routes/_app/dsa/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as AppCaseStudiesIndexRouteImport } from './routes/_app/case-studies/index'
import { Route as AppAssessmentsIndexRouteImport } from './routes/_app/assessments/index'
import { Route as AppProfileCertificatesRouteImport } from './routes/_app/profile/certificates'
import { Route as AppProfileAchievementsRouteImport } from './routes/_app/profile/achievements'
import { Route as AppLearnRoadmapsRouteImport } from './routes/_app/learn/roadmaps'
import { Route as AppLearnNotesRouteImport } from './routes/_app/learn/notes'
import { Route as AppInterviewQaTypeRouteImport } from './routes/_app/interview-qa/$type'
import { Route as AppEventsTypeRouteImport } from './routes/_app/events/$type'
import { Route as AppDsaTopicIdRouteImport } from './routes/_app/dsa/$topicId'
import { Route as AppDashboardAiDashboardRouteImport } from './routes/_app/dashboard/ai-dashboard'
import { Route as AppCoursesBookmarksRouteImport } from './routes/_app/courses/bookmarks'
import { Route as AppCaseStudiesTypeRouteImport } from './routes/_app/case-studies/$type'
import { Route as AppAssessmentsTypeRouteImport } from './routes/_app/assessments/$type'
import { Route as AppAiResearchRouteImport } from './routes/_app/ai/research'
import { Route as AppAiChatRouteImport } from './routes/_app/ai/chat'
import { Route as AppPracticeInterviewQaIndexRouteImport } from './routes/_app/practice/interview-qa/index'
import { Route as AppPracticeDsaIndexRouteImport } from './routes/_app/practice/dsa/index'
import { Route as AppPracticeCaseStudiesIndexRouteImport } from './routes/_app/practice/case-studies/index'
import { Route as AppPracticeAssessmentsIndexRouteImport } from './routes/_app/practice/assessments/index'
import { Route as AppCoursesCourseIdIndexRouteImport } from './routes/_app/courses/$courseId/index'
import { Route as AppPracticeProblemProblemIdRouteImport } from './routes/_app/practice/problem/$problemId'
import { Route as AppPracticeInterviewQaTypeRouteImport } from './routes/_app/practice/interview-qa/$type'
import { Route as AppPracticeDsaTopicIdRouteImport } from './routes/_app/practice/dsa/$topicId'
import { Route as AppPracticeCaseStudiesTypeRouteImport } from './routes/_app/practice/case-studies/$type'
import { Route as AppPracticeAssessmentsTypeRouteImport } from './routes/_app/practice/assessments/$type'
import { Route as AppCoursesCourseIdArticlesRouteImport } from './routes/_app/courses/$courseId/articles'
import { Route as AppPracticeDsaTopicIdIndexRouteImport } from './routes/_app/practice/dsa/$topicId/index'
import { Route as AppPracticeDsaTopicIdRoadmapRouteImport } from './routes/_app/practice/dsa/$topicId/roadmap'
import { Route as AppPracticeDsaTopicIdRevisionRouteImport } from './routes/_app/practice/dsa/$topicId/revision'
import { Route as AppPracticeDsaTopicIdResourcesRouteImport } from './routes/_app/practice/dsa/$topicId/resources'
import { Route as AppPracticeDsaTopicIdInterviewRouteImport } from './routes/_app/practice/dsa/$topicId/interview'
import { Route as AppPracticeDsaTopicIdCopilotRouteImport } from './routes/_app/practice/dsa/$topicId/copilot'
import { Route as AppCoursesCourseIdModulesModuleIdIndexRouteImport } from './routes/_app/courses/$courseId/modules/$moduleId/index'
import { Route as AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRouteImport } from './routes/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentationRoute = AppDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeIndexRoute = AppPracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPracticeRoute,
} as any)
const AppLearnIndexRoute = AppLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewQaIndexRoute = AppInterviewQaIndexRouteImport.update({
  id: '/interview-qa/',
  path: '/interview-qa/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppDsaIndexRoute = AppDsaIndexRouteImport.update({
  id: '/dsa/',
  path: '/dsa/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseStudiesIndexRoute = AppCaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsIndexRoute = AppAssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileCertificatesRoute = AppProfileCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileAchievementsRoute = AppProfileAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppLearnRoadmapsRoute = AppLearnRoadmapsRouteImport.update({
  id: '/learn/roadmaps',
  path: '/learn/roadmaps',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnNotesRoute = AppLearnNotesRouteImport.update({
  id: '/learn/notes',
  path: '/learn/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewQaTypeRoute = AppInterviewQaTypeRouteImport.update({
  id: '/interview-qa/$type',
  path: '/interview-qa/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsTypeRoute = AppEventsTypeRouteImport.update({
  id: '/events/$type',
  path: '/events/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppDsaTopicIdRoute = AppDsaTopicIdRouteImport.update({
  id: '/dsa/$topicId',
  path: '/dsa/$topicId',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardAiDashboardRoute = AppDashboardAiDashboardRouteImport.update({
  id: '/dashboard/ai-dashboard',
  path: '/dashboard/ai-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesBookmarksRoute = AppCoursesBookmarksRouteImport.update({
  id: '/courses/bookmarks',
  path: '/courses/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppCaseStudiesTypeRoute = AppCaseStudiesTypeRouteImport.update({
  id: '/case-studies/$type',
  path: '/case-studies/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsTypeRoute = AppAssessmentsTypeRouteImport.update({
  id: '/assessments/$type',
  path: '/assessments/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppAiResearchRoute = AppAiResearchRouteImport.update({
  id: '/ai/research',
  path: '/ai/research',
  getParentRoute: () => AppRoute,
} as any)
const AppAiChatRoute = AppAiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeInterviewQaIndexRoute =
  AppPracticeInterviewQaIndexRouteImport.update({
    id: '/interview-qa/',
    path: '/interview-qa/',
    getParentRoute: () => AppPracticeRoute,
  } as any)
const AppPracticeDsaIndexRoute = AppPracticeDsaIndexRouteImport.update({
  id: '/dsa/',
  path: '/dsa/',
  getParentRoute: () => AppPracticeRoute,
} as any)
const AppPracticeCaseStudiesIndexRoute =
  AppPracticeCaseStudiesIndexRouteImport.update({
    id: '/case-studies/',
    path: '/case-studies/',
    getParentRoute: () => AppPracticeRoute,
  } as any)
const AppPracticeAssessmentsIndexRoute =
  AppPracticeAssessmentsIndexRouteImport.update({
    id: '/assessments/',
    path: '/assessments/',
    getParentRoute: () => AppPracticeRoute,
  } as any)
const AppCoursesCourseIdIndexRoute = AppCoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeProblemProblemIdRoute =
  AppPracticeProblemProblemIdRouteImport.update({
    id: '/problem/$problemId',
    path: '/problem/$problemId',
    getParentRoute: () => AppPracticeRoute,
  } as any)
const AppPracticeInterviewQaTypeRoute =
  AppPracticeInterviewQaTypeRouteImport.update({
    id: '/interview-qa/$type',
    path: '/interview-qa/$type',
    getParentRoute: () => AppPracticeRoute,
  } as any)
const AppPracticeDsaTopicIdRoute = AppPracticeDsaTopicIdRouteImport.update({
  id: '/dsa/$topicId',
  path: '/dsa/$topicId',
  getParentRoute: () => AppPracticeRoute,
} as any)
const AppPracticeCaseStudiesTypeRoute =
  AppPracticeCaseStudiesTypeRouteImport.update({
    id: '/case-studies/$type',
    path: '/case-studies/$type',
    getParentRoute: () => AppPracticeRoute,
  } as any)
const AppPracticeAssessmentsTypeRoute =
  AppPracticeAssessmentsTypeRouteImport.update({
    id: '/assessments/$type',
    path: '/assessments/$type',
    getParentRoute: () => AppPracticeRoute,
  } as any)
const AppCoursesCourseIdArticlesRoute =
  AppCoursesCourseIdArticlesRouteImport.update({
    id: '/courses/$courseId/articles',
    path: '/courses/$courseId/articles',
    getParentRoute: () => AppRoute,
  } as any)
const AppPracticeDsaTopicIdIndexRoute =
  AppPracticeDsaTopicIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPracticeDsaTopicIdRoute,
  } as any)
const AppPracticeDsaTopicIdRoadmapRoute =
  AppPracticeDsaTopicIdRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => AppPracticeDsaTopicIdRoute,
  } as any)
const AppPracticeDsaTopicIdRevisionRoute =
  AppPracticeDsaTopicIdRevisionRouteImport.update({
    id: '/revision',
    path: '/revision',
    getParentRoute: () => AppPracticeDsaTopicIdRoute,
  } as any)
const AppPracticeDsaTopicIdResourcesRoute =
  AppPracticeDsaTopicIdResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AppPracticeDsaTopicIdRoute,
  } as any)
const AppPracticeDsaTopicIdInterviewRoute =
  AppPracticeDsaTopicIdInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AppPracticeDsaTopicIdRoute,
  } as any)
const AppPracticeDsaTopicIdCopilotRoute =
  AppPracticeDsaTopicIdCopilotRouteImport.update({
    id: '/copilot',
    path: '/copilot',
    getParentRoute: () => AppPracticeDsaTopicIdRoute,
  } as any)
const AppCoursesCourseIdModulesModuleIdIndexRoute =
  AppCoursesCourseIdModulesModuleIdIndexRouteImport.update({
    id: '/courses/$courseId/modules/$moduleId/',
    path: '/courses/$courseId/modules/$moduleId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute =
  AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRouteImport.update({
    id: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/',
    path: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof AppCommunityRoute
  '/documentation': typeof AppDocumentationRoute
  '/help': typeof AppHelpRoute
  '/practice': typeof AppPracticeRouteWithChildren
  '/profile': typeof AppProfileRouteWithChildren
  '/research': typeof AppResearchRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/ai/chat': typeof AppAiChatRoute
  '/ai/research': typeof AppAiResearchRoute
  '/assessments/$type': typeof AppAssessmentsTypeRoute
  '/case-studies/$type': typeof AppCaseStudiesTypeRoute
  '/courses/bookmarks': typeof AppCoursesBookmarksRoute
  '/dashboard/ai-dashboard': typeof AppDashboardAiDashboardRoute
  '/dsa/$topicId': typeof AppDsaTopicIdRoute
  '/events/$type': typeof AppEventsTypeRoute
  '/interview-qa/$type': typeof AppInterviewQaTypeRoute
  '/learn/notes': typeof AppLearnNotesRoute
  '/learn/roadmaps': typeof AppLearnRoadmapsRoute
  '/profile/achievements': typeof AppProfileAchievementsRoute
  '/profile/certificates': typeof AppProfileCertificatesRoute
  '/assessments/': typeof AppAssessmentsIndexRoute
  '/case-studies/': typeof AppCaseStudiesIndexRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dsa/': typeof AppDsaIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/interview-qa/': typeof AppInterviewQaIndexRoute
  '/learn/': typeof AppLearnIndexRoute
  '/practice/': typeof AppPracticeIndexRoute
  '/courses/$courseId/articles': typeof AppCoursesCourseIdArticlesRoute
  '/practice/assessments/$type': typeof AppPracticeAssessmentsTypeRoute
  '/practice/case-studies/$type': typeof AppPracticeCaseStudiesTypeRoute
  '/practice/dsa/$topicId': typeof AppPracticeDsaTopicIdRouteWithChildren
  '/practice/interview-qa/$type': typeof AppPracticeInterviewQaTypeRoute
  '/practice/problem/$problemId': typeof AppPracticeProblemProblemIdRoute
  '/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/practice/assessments/': typeof AppPracticeAssessmentsIndexRoute
  '/practice/case-studies/': typeof AppPracticeCaseStudiesIndexRoute
  '/practice/dsa/': typeof AppPracticeDsaIndexRoute
  '/practice/interview-qa/': typeof AppPracticeInterviewQaIndexRoute
  '/practice/dsa/$topicId/copilot': typeof AppPracticeDsaTopicIdCopilotRoute
  '/practice/dsa/$topicId/interview': typeof AppPracticeDsaTopicIdInterviewRoute
  '/practice/dsa/$topicId/resources': typeof AppPracticeDsaTopicIdResourcesRoute
  '/practice/dsa/$topicId/revision': typeof AppPracticeDsaTopicIdRevisionRoute
  '/practice/dsa/$topicId/roadmap': typeof AppPracticeDsaTopicIdRoadmapRoute
  '/practice/dsa/$topicId/': typeof AppPracticeDsaTopicIdIndexRoute
  '/courses/$courseId/modules/$moduleId/': typeof AppCoursesCourseIdModulesModuleIdIndexRoute
  '/courses/$courseId/modules/$moduleId/lessons/$lessonId/': typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof AppCommunityRoute
  '/documentation': typeof AppDocumentationRoute
  '/help': typeof AppHelpRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/research': typeof AppResearchRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/ai/chat': typeof AppAiChatRoute
  '/ai/research': typeof AppAiResearchRoute
  '/assessments/$type': typeof AppAssessmentsTypeRoute
  '/case-studies/$type': typeof AppCaseStudiesTypeRoute
  '/courses/bookmarks': typeof AppCoursesBookmarksRoute
  '/dashboard/ai-dashboard': typeof AppDashboardAiDashboardRoute
  '/dsa/$topicId': typeof AppDsaTopicIdRoute
  '/events/$type': typeof AppEventsTypeRoute
  '/interview-qa/$type': typeof AppInterviewQaTypeRoute
  '/learn/notes': typeof AppLearnNotesRoute
  '/learn/roadmaps': typeof AppLearnRoadmapsRoute
  '/profile/achievements': typeof AppProfileAchievementsRoute
  '/profile/certificates': typeof AppProfileCertificatesRoute
  '/assessments': typeof AppAssessmentsIndexRoute
  '/case-studies': typeof AppCaseStudiesIndexRoute
  '/courses': typeof AppCoursesIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dsa': typeof AppDsaIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/interview-qa': typeof AppInterviewQaIndexRoute
  '/learn': typeof AppLearnIndexRoute
  '/practice': typeof AppPracticeIndexRoute
  '/courses/$courseId/articles': typeof AppCoursesCourseIdArticlesRoute
  '/practice/assessments/$type': typeof AppPracticeAssessmentsTypeRoute
  '/practice/case-studies/$type': typeof AppPracticeCaseStudiesTypeRoute
  '/practice/interview-qa/$type': typeof AppPracticeInterviewQaTypeRoute
  '/practice/problem/$problemId': typeof AppPracticeProblemProblemIdRoute
  '/courses/$courseId': typeof AppCoursesCourseIdIndexRoute
  '/practice/assessments': typeof AppPracticeAssessmentsIndexRoute
  '/practice/case-studies': typeof AppPracticeCaseStudiesIndexRoute
  '/practice/dsa': typeof AppPracticeDsaIndexRoute
  '/practice/interview-qa': typeof AppPracticeInterviewQaIndexRoute
  '/practice/dsa/$topicId/copilot': typeof AppPracticeDsaTopicIdCopilotRoute
  '/practice/dsa/$topicId/interview': typeof AppPracticeDsaTopicIdInterviewRoute
  '/practice/dsa/$topicId/resources': typeof AppPracticeDsaTopicIdResourcesRoute
  '/practice/dsa/$topicId/revision': typeof AppPracticeDsaTopicIdRevisionRoute
  '/practice/dsa/$topicId/roadmap': typeof AppPracticeDsaTopicIdRoadmapRoute
  '/practice/dsa/$topicId': typeof AppPracticeDsaTopicIdIndexRoute
  '/courses/$courseId/modules/$moduleId': typeof AppCoursesCourseIdModulesModuleIdIndexRoute
  '/courses/$courseId/modules/$moduleId/lessons/$lessonId': typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/community': typeof AppCommunityRoute
  '/_app/documentation': typeof AppDocumentationRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/practice': typeof AppPracticeRouteWithChildren
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/research': typeof AppResearchRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/ai/chat': typeof AppAiChatRoute
  '/_app/ai/research': typeof AppAiResearchRoute
  '/_app/assessments/$type': typeof AppAssessmentsTypeRoute
  '/_app/case-studies/$type': typeof AppCaseStudiesTypeRoute
  '/_app/courses/bookmarks': typeof AppCoursesBookmarksRoute
  '/_app/dashboard/ai-dashboard': typeof AppDashboardAiDashboardRoute
  '/_app/dsa/$topicId': typeof AppDsaTopicIdRoute
  '/_app/events/$type': typeof AppEventsTypeRoute
  '/_app/interview-qa/$type': typeof AppInterviewQaTypeRoute
  '/_app/learn/notes': typeof AppLearnNotesRoute
  '/_app/learn/roadmaps': typeof AppLearnRoadmapsRoute
  '/_app/profile/achievements': typeof AppProfileAchievementsRoute
  '/_app/profile/certificates': typeof AppProfileCertificatesRoute
  '/_app/assessments/': typeof AppAssessmentsIndexRoute
  '/_app/case-studies/': typeof AppCaseStudiesIndexRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dsa/': typeof AppDsaIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/interview-qa/': typeof AppInterviewQaIndexRoute
  '/_app/learn/': typeof AppLearnIndexRoute
  '/_app/practice/': typeof AppPracticeIndexRoute
  '/_app/courses/$courseId/articles': typeof AppCoursesCourseIdArticlesRoute
  '/_app/practice/assessments/$type': typeof AppPracticeAssessmentsTypeRoute
  '/_app/practice/case-studies/$type': typeof AppPracticeCaseStudiesTypeRoute
  '/_app/practice/dsa/$topicId': typeof AppPracticeDsaTopicIdRouteWithChildren
  '/_app/practice/interview-qa/$type': typeof AppPracticeInterviewQaTypeRoute
  '/_app/practice/problem/$problemId': typeof AppPracticeProblemProblemIdRoute
  '/_app/courses/$courseId/': typeof AppCoursesCourseIdIndexRoute
  '/_app/practice/assessments/': typeof AppPracticeAssessmentsIndexRoute
  '/_app/practice/case-studies/': typeof AppPracticeCaseStudiesIndexRoute
  '/_app/practice/dsa/': typeof AppPracticeDsaIndexRoute
  '/_app/practice/interview-qa/': typeof AppPracticeInterviewQaIndexRoute
  '/_app/practice/dsa/$topicId/copilot': typeof AppPracticeDsaTopicIdCopilotRoute
  '/_app/practice/dsa/$topicId/interview': typeof AppPracticeDsaTopicIdInterviewRoute
  '/_app/practice/dsa/$topicId/resources': typeof AppPracticeDsaTopicIdResourcesRoute
  '/_app/practice/dsa/$topicId/revision': typeof AppPracticeDsaTopicIdRevisionRoute
  '/_app/practice/dsa/$topicId/roadmap': typeof AppPracticeDsaTopicIdRoadmapRoute
  '/_app/practice/dsa/$topicId/': typeof AppPracticeDsaTopicIdIndexRoute
  '/_app/courses/$courseId/modules/$moduleId/': typeof AppCoursesCourseIdModulesModuleIdIndexRoute
  '/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/': typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/documentation'
    | '/help'
    | '/practice'
    | '/profile'
    | '/research'
    | '/login'
    | '/signup'
    | '/ai/chat'
    | '/ai/research'
    | '/assessments/$type'
    | '/case-studies/$type'
    | '/courses/bookmarks'
    | '/dashboard/ai-dashboard'
    | '/dsa/$topicId'
    | '/events/$type'
    | '/interview-qa/$type'
    | '/learn/notes'
    | '/learn/roadmaps'
    | '/profile/achievements'
    | '/profile/certificates'
    | '/assessments/'
    | '/case-studies/'
    | '/courses/'
    | '/dashboard/'
    | '/dsa/'
    | '/events/'
    | '/interview-qa/'
    | '/learn/'
    | '/practice/'
    | '/courses/$courseId/articles'
    | '/practice/assessments/$type'
    | '/practice/case-studies/$type'
    | '/practice/dsa/$topicId'
    | '/practice/interview-qa/$type'
    | '/practice/problem/$problemId'
    | '/courses/$courseId/'
    | '/practice/assessments/'
    | '/practice/case-studies/'
    | '/practice/dsa/'
    | '/practice/interview-qa/'
    | '/practice/dsa/$topicId/copilot'
    | '/practice/dsa/$topicId/interview'
    | '/practice/dsa/$topicId/resources'
    | '/practice/dsa/$topicId/revision'
    | '/practice/dsa/$topicId/roadmap'
    | '/practice/dsa/$topicId/'
    | '/courses/$courseId/modules/$moduleId/'
    | '/courses/$courseId/modules/$moduleId/lessons/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/documentation'
    | '/help'
    | '/profile'
    | '/research'
    | '/login'
    | '/signup'
    | '/ai/chat'
    | '/ai/research'
    | '/assessments/$type'
    | '/case-studies/$type'
    | '/courses/bookmarks'
    | '/dashboard/ai-dashboard'
    | '/dsa/$topicId'
    | '/events/$type'
    | '/interview-qa/$type'
    | '/learn/notes'
    | '/learn/roadmaps'
    | '/profile/achievements'
    | '/profile/certificates'
    | '/assessments'
    | '/case-studies'
    | '/courses'
    | '/dashboard'
    | '/dsa'
    | '/events'
    | '/interview-qa'
    | '/learn'
    | '/practice'
    | '/courses/$courseId/articles'
    | '/practice/assessments/$type'
    | '/practice/case-studies/$type'
    | '/practice/interview-qa/$type'
    | '/practice/problem/$problemId'
    | '/courses/$courseId'
    | '/practice/assessments'
    | '/practice/case-studies'
    | '/practice/dsa'
    | '/practice/interview-qa'
    | '/practice/dsa/$topicId/copilot'
    | '/practice/dsa/$topicId/interview'
    | '/practice/dsa/$topicId/resources'
    | '/practice/dsa/$topicId/revision'
    | '/practice/dsa/$topicId/roadmap'
    | '/practice/dsa/$topicId'
    | '/courses/$courseId/modules/$moduleId'
    | '/courses/$courseId/modules/$moduleId/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/community'
    | '/_app/documentation'
    | '/_app/help'
    | '/_app/practice'
    | '/_app/profile'
    | '/_app/research'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/ai/chat'
    | '/_app/ai/research'
    | '/_app/assessments/$type'
    | '/_app/case-studies/$type'
    | '/_app/courses/bookmarks'
    | '/_app/dashboard/ai-dashboard'
    | '/_app/dsa/$topicId'
    | '/_app/events/$type'
    | '/_app/interview-qa/$type'
    | '/_app/learn/notes'
    | '/_app/learn/roadmaps'
    | '/_app/profile/achievements'
    | '/_app/profile/certificates'
    | '/_app/assessments/'
    | '/_app/case-studies/'
    | '/_app/courses/'
    | '/_app/dashboard/'
    | '/_app/dsa/'
    | '/_app/events/'
    | '/_app/interview-qa/'
    | '/_app/learn/'
    | '/_app/practice/'
    | '/_app/courses/$courseId/articles'
    | '/_app/practice/assessments/$type'
    | '/_app/practice/case-studies/$type'
    | '/_app/practice/dsa/$topicId'
    | '/_app/practice/interview-qa/$type'
    | '/_app/practice/problem/$problemId'
    | '/_app/courses/$courseId/'
    | '/_app/practice/assessments/'
    | '/_app/practice/case-studies/'
    | '/_app/practice/dsa/'
    | '/_app/practice/interview-qa/'
    | '/_app/practice/dsa/$topicId/copilot'
    | '/_app/practice/dsa/$topicId/interview'
    | '/_app/practice/dsa/$topicId/resources'
    | '/_app/practice/dsa/$topicId/revision'
    | '/_app/practice/dsa/$topicId/roadmap'
    | '/_app/practice/dsa/$topicId/'
    | '/_app/courses/$courseId/modules/$moduleId/'
    | '/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/research': {
      id: '/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentation': {
      id: '/_app/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof AppDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/': {
      id: '/_app/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof AppPracticeIndexRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/learn/': {
      id: '/_app/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AppLearnIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview-qa/': {
      id: '/_app/interview-qa/'
      path: '/interview-qa'
      fullPath: '/interview-qa/'
      preLoaderRoute: typeof AppInterviewQaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dsa/': {
      id: '/_app/dsa/'
      path: '/dsa'
      fullPath: '/dsa/'
      preLoaderRoute: typeof AppDsaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-studies/': {
      id: '/_app/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof AppCaseStudiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessments/': {
      id: '/_app/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AppAssessmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/certificates': {
      id: '/_app/profile/certificates'
      path: '/certificates'
      fullPath: '/profile/certificates'
      preLoaderRoute: typeof AppProfileCertificatesRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/achievements': {
      id: '/_app/profile/achievements'
      path: '/achievements'
      fullPath: '/profile/achievements'
      preLoaderRoute: typeof AppProfileAchievementsRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/learn/roadmaps': {
      id: '/_app/learn/roadmaps'
      path: '/learn/roadmaps'
      fullPath: '/learn/roadmaps'
      preLoaderRoute: typeof AppLearnRoadmapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/notes': {
      id: '/_app/learn/notes'
      path: '/learn/notes'
      fullPath: '/learn/notes'
      preLoaderRoute: typeof AppLearnNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview-qa/$type': {
      id: '/_app/interview-qa/$type'
      path: '/interview-qa/$type'
      fullPath: '/interview-qa/$type'
      preLoaderRoute: typeof AppInterviewQaTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$type': {
      id: '/_app/events/$type'
      path: '/events/$type'
      fullPath: '/events/$type'
      preLoaderRoute: typeof AppEventsTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dsa/$topicId': {
      id: '/_app/dsa/$topicId'
      path: '/dsa/$topicId'
      fullPath: '/dsa/$topicId'
      preLoaderRoute: typeof AppDsaTopicIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/ai-dashboard': {
      id: '/_app/dashboard/ai-dashboard'
      path: '/dashboard/ai-dashboard'
      fullPath: '/dashboard/ai-dashboard'
      preLoaderRoute: typeof AppDashboardAiDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/bookmarks': {
      id: '/_app/courses/bookmarks'
      path: '/courses/bookmarks'
      fullPath: '/courses/bookmarks'
      preLoaderRoute: typeof AppCoursesBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/case-studies/$type': {
      id: '/_app/case-studies/$type'
      path: '/case-studies/$type'
      fullPath: '/case-studies/$type'
      preLoaderRoute: typeof AppCaseStudiesTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessments/$type': {
      id: '/_app/assessments/$type'
      path: '/assessments/$type'
      fullPath: '/assessments/$type'
      preLoaderRoute: typeof AppAssessmentsTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/research': {
      id: '/_app/ai/research'
      path: '/ai/research'
      fullPath: '/ai/research'
      preLoaderRoute: typeof AppAiResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/chat': {
      id: '/_app/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AppAiChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/interview-qa/': {
      id: '/_app/practice/interview-qa/'
      path: '/interview-qa'
      fullPath: '/practice/interview-qa/'
      preLoaderRoute: typeof AppPracticeInterviewQaIndexRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/practice/dsa/': {
      id: '/_app/practice/dsa/'
      path: '/dsa'
      fullPath: '/practice/dsa/'
      preLoaderRoute: typeof AppPracticeDsaIndexRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/practice/case-studies/': {
      id: '/_app/practice/case-studies/'
      path: '/case-studies'
      fullPath: '/practice/case-studies/'
      preLoaderRoute: typeof AppPracticeCaseStudiesIndexRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/practice/assessments/': {
      id: '/_app/practice/assessments/'
      path: '/assessments'
      fullPath: '/practice/assessments/'
      preLoaderRoute: typeof AppPracticeAssessmentsIndexRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/courses/$courseId/': {
      id: '/_app/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof AppCoursesCourseIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/problem/$problemId': {
      id: '/_app/practice/problem/$problemId'
      path: '/problem/$problemId'
      fullPath: '/practice/problem/$problemId'
      preLoaderRoute: typeof AppPracticeProblemProblemIdRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/practice/interview-qa/$type': {
      id: '/_app/practice/interview-qa/$type'
      path: '/interview-qa/$type'
      fullPath: '/practice/interview-qa/$type'
      preLoaderRoute: typeof AppPracticeInterviewQaTypeRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/practice/dsa/$topicId': {
      id: '/_app/practice/dsa/$topicId'
      path: '/dsa/$topicId'
      fullPath: '/practice/dsa/$topicId'
      preLoaderRoute: typeof AppPracticeDsaTopicIdRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/practice/case-studies/$type': {
      id: '/_app/practice/case-studies/$type'
      path: '/case-studies/$type'
      fullPath: '/practice/case-studies/$type'
      preLoaderRoute: typeof AppPracticeCaseStudiesTypeRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/practice/assessments/$type': {
      id: '/_app/practice/assessments/$type'
      path: '/assessments/$type'
      fullPath: '/practice/assessments/$type'
      preLoaderRoute: typeof AppPracticeAssessmentsTypeRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/courses/$courseId/articles': {
      id: '/_app/courses/$courseId/articles'
      path: '/courses/$courseId/articles'
      fullPath: '/courses/$courseId/articles'
      preLoaderRoute: typeof AppCoursesCourseIdArticlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/dsa/$topicId/': {
      id: '/_app/practice/dsa/$topicId/'
      path: '/'
      fullPath: '/practice/dsa/$topicId/'
      preLoaderRoute: typeof AppPracticeDsaTopicIdIndexRouteImport
      parentRoute: typeof AppPracticeDsaTopicIdRoute
    }
    '/_app/practice/dsa/$topicId/roadmap': {
      id: '/_app/practice/dsa/$topicId/roadmap'
      path: '/roadmap'
      fullPath: '/practice/dsa/$topicId/roadmap'
      preLoaderRoute: typeof AppPracticeDsaTopicIdRoadmapRouteImport
      parentRoute: typeof AppPracticeDsaTopicIdRoute
    }
    '/_app/practice/dsa/$topicId/revision': {
      id: '/_app/practice/dsa/$topicId/revision'
      path: '/revision'
      fullPath: '/practice/dsa/$topicId/revision'
      preLoaderRoute: typeof AppPracticeDsaTopicIdRevisionRouteImport
      parentRoute: typeof AppPracticeDsaTopicIdRoute
    }
    '/_app/practice/dsa/$topicId/resources': {
      id: '/_app/practice/dsa/$topicId/resources'
      path: '/resources'
      fullPath: '/practice/dsa/$topicId/resources'
      preLoaderRoute: typeof AppPracticeDsaTopicIdResourcesRouteImport
      parentRoute: typeof AppPracticeDsaTopicIdRoute
    }
    '/_app/practice/dsa/$topicId/interview': {
      id: '/_app/practice/dsa/$topicId/interview'
      path: '/interview'
      fullPath: '/practice/dsa/$topicId/interview'
      preLoaderRoute: typeof AppPracticeDsaTopicIdInterviewRouteImport
      parentRoute: typeof AppPracticeDsaTopicIdRoute
    }
    '/_app/practice/dsa/$topicId/copilot': {
      id: '/_app/practice/dsa/$topicId/copilot'
      path: '/copilot'
      fullPath: '/practice/dsa/$topicId/copilot'
      preLoaderRoute: typeof AppPracticeDsaTopicIdCopilotRouteImport
      parentRoute: typeof AppPracticeDsaTopicIdRoute
    }
    '/_app/courses/$courseId/modules/$moduleId/': {
      id: '/_app/courses/$courseId/modules/$moduleId/'
      path: '/courses/$courseId/modules/$moduleId'
      fullPath: '/courses/$courseId/modules/$moduleId/'
      preLoaderRoute: typeof AppCoursesCourseIdModulesModuleIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/': {
      id: '/_app/courses/$courseId/modules/$moduleId/lessons/$lessonId/'
      path: '/courses/$courseId/modules/$moduleId/lessons/$lessonId'
      fullPath: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/'
      preLoaderRoute: typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPracticeDsaTopicIdRouteChildren {
  AppPracticeDsaTopicIdCopilotRoute: typeof AppPracticeDsaTopicIdCopilotRoute
  AppPracticeDsaTopicIdInterviewRoute: typeof AppPracticeDsaTopicIdInterviewRoute
  AppPracticeDsaTopicIdResourcesRoute: typeof AppPracticeDsaTopicIdResourcesRoute
  AppPracticeDsaTopicIdRevisionRoute: typeof AppPracticeDsaTopicIdRevisionRoute
  AppPracticeDsaTopicIdRoadmapRoute: typeof AppPracticeDsaTopicIdRoadmapRoute
  AppPracticeDsaTopicIdIndexRoute: typeof AppPracticeDsaTopicIdIndexRoute
}

const AppPracticeDsaTopicIdRouteChildren: AppPracticeDsaTopicIdRouteChildren = {
  AppPracticeDsaTopicIdCopilotRoute: AppPracticeDsaTopicIdCopilotRoute,
  AppPracticeDsaTopicIdInterviewRoute: AppPracticeDsaTopicIdInterviewRoute,
  AppPracticeDsaTopicIdResourcesRoute: AppPracticeDsaTopicIdResourcesRoute,
  AppPracticeDsaTopicIdRevisionRoute: AppPracticeDsaTopicIdRevisionRoute,
  AppPracticeDsaTopicIdRoadmapRoute: AppPracticeDsaTopicIdRoadmapRoute,
  AppPracticeDsaTopicIdIndexRoute: AppPracticeDsaTopicIdIndexRoute,
}

const AppPracticeDsaTopicIdRouteWithChildren =
  AppPracticeDsaTopicIdRoute._addFileChildren(
    AppPracticeDsaTopicIdRouteChildren,
  )

interface AppPracticeRouteChildren {
  AppPracticeIndexRoute: typeof AppPracticeIndexRoute
  AppPracticeAssessmentsTypeRoute: typeof AppPracticeAssessmentsTypeRoute
  AppPracticeCaseStudiesTypeRoute: typeof AppPracticeCaseStudiesTypeRoute
  AppPracticeDsaTopicIdRoute: typeof AppPracticeDsaTopicIdRouteWithChildren
  AppPracticeInterviewQaTypeRoute: typeof AppPracticeInterviewQaTypeRoute
  AppPracticeProblemProblemIdRoute: typeof AppPracticeProblemProblemIdRoute
  AppPracticeAssessmentsIndexRoute: typeof AppPracticeAssessmentsIndexRoute
  AppPracticeCaseStudiesIndexRoute: typeof AppPracticeCaseStudiesIndexRoute
  AppPracticeDsaIndexRoute: typeof AppPracticeDsaIndexRoute
  AppPracticeInterviewQaIndexRoute: typeof AppPracticeInterviewQaIndexRoute
}

const AppPracticeRouteChildren: AppPracticeRouteChildren = {
  AppPracticeIndexRoute: AppPracticeIndexRoute,
  AppPracticeAssessmentsTypeRoute: AppPracticeAssessmentsTypeRoute,
  AppPracticeCaseStudiesTypeRoute: AppPracticeCaseStudiesTypeRoute,
  AppPracticeDsaTopicIdRoute: AppPracticeDsaTopicIdRouteWithChildren,
  AppPracticeInterviewQaTypeRoute: AppPracticeInterviewQaTypeRoute,
  AppPracticeProblemProblemIdRoute: AppPracticeProblemProblemIdRoute,
  AppPracticeAssessmentsIndexRoute: AppPracticeAssessmentsIndexRoute,
  AppPracticeCaseStudiesIndexRoute: AppPracticeCaseStudiesIndexRoute,
  AppPracticeDsaIndexRoute: AppPracticeDsaIndexRoute,
  AppPracticeInterviewQaIndexRoute: AppPracticeInterviewQaIndexRoute,
}

const AppPracticeRouteWithChildren = AppPracticeRoute._addFileChildren(
  AppPracticeRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileAchievementsRoute: typeof AppProfileAchievementsRoute
  AppProfileCertificatesRoute: typeof AppProfileCertificatesRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileAchievementsRoute: AppProfileAchievementsRoute,
  AppProfileCertificatesRoute: AppProfileCertificatesRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppCommunityRoute: typeof AppCommunityRoute
  AppDocumentationRoute: typeof AppDocumentationRoute
  AppHelpRoute: typeof AppHelpRoute
  AppPracticeRoute: typeof AppPracticeRouteWithChildren
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppResearchRoute: typeof AppResearchRoute
  AppAiChatRoute: typeof AppAiChatRoute
  AppAiResearchRoute: typeof AppAiResearchRoute
  AppAssessmentsTypeRoute: typeof AppAssessmentsTypeRoute
  AppCaseStudiesTypeRoute: typeof AppCaseStudiesTypeRoute
  AppCoursesBookmarksRoute: typeof AppCoursesBookmarksRoute
  AppDashboardAiDashboardRoute: typeof AppDashboardAiDashboardRoute
  AppDsaTopicIdRoute: typeof AppDsaTopicIdRoute
  AppEventsTypeRoute: typeof AppEventsTypeRoute
  AppInterviewQaTypeRoute: typeof AppInterviewQaTypeRoute
  AppLearnNotesRoute: typeof AppLearnNotesRoute
  AppLearnRoadmapsRoute: typeof AppLearnRoadmapsRoute
  AppAssessmentsIndexRoute: typeof AppAssessmentsIndexRoute
  AppCaseStudiesIndexRoute: typeof AppCaseStudiesIndexRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDsaIndexRoute: typeof AppDsaIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppInterviewQaIndexRoute: typeof AppInterviewQaIndexRoute
  AppLearnIndexRoute: typeof AppLearnIndexRoute
  AppCoursesCourseIdArticlesRoute: typeof AppCoursesCourseIdArticlesRoute
  AppCoursesCourseIdIndexRoute: typeof AppCoursesCourseIdIndexRoute
  AppCoursesCourseIdModulesModuleIdIndexRoute: typeof AppCoursesCourseIdModulesModuleIdIndexRoute
  AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute: typeof AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCommunityRoute: AppCommunityRoute,
  AppDocumentationRoute: AppDocumentationRoute,
  AppHelpRoute: AppHelpRoute,
  AppPracticeRoute: AppPracticeRouteWithChildren,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppResearchRoute: AppResearchRoute,
  AppAiChatRoute: AppAiChatRoute,
  AppAiResearchRoute: AppAiResearchRoute,
  AppAssessmentsTypeRoute: AppAssessmentsTypeRoute,
  AppCaseStudiesTypeRoute: AppCaseStudiesTypeRoute,
  AppCoursesBookmarksRoute: AppCoursesBookmarksRoute,
  AppDashboardAiDashboardRoute: AppDashboardAiDashboardRoute,
  AppDsaTopicIdRoute: AppDsaTopicIdRoute,
  AppEventsTypeRoute: AppEventsTypeRoute,
  AppInterviewQaTypeRoute: AppInterviewQaTypeRoute,
  AppLearnNotesRoute: AppLearnNotesRoute,
  AppLearnRoadmapsRoute: AppLearnRoadmapsRoute,
  AppAssessmentsIndexRoute: AppAssessmentsIndexRoute,
  AppCaseStudiesIndexRoute: AppCaseStudiesIndexRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDsaIndexRoute: AppDsaIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppInterviewQaIndexRoute: AppInterviewQaIndexRoute,
  AppLearnIndexRoute: AppLearnIndexRoute,
  AppCoursesCourseIdArticlesRoute: AppCoursesCourseIdArticlesRoute,
  AppCoursesCourseIdIndexRoute: AppCoursesCourseIdIndexRoute,
  AppCoursesCourseIdModulesModuleIdIndexRoute:
    AppCoursesCourseIdModulesModuleIdIndexRoute,
  AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute:
    AppCoursesCourseIdModulesModuleIdLessonsLessonIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
